/**
 * Gemma Health Edge — Core Utilities
 * 
 * Bundled: i18n, storage, config, PDF export, medical helpers.
 * Optimized for local-first, privacy-conscious medical AI.
 */

// ── Internationalization ──────────────────────────────────────────────────────

const dictionary = {
  en: { 
    appTitle: "Gemma Health Edge",
    disclaimer_title: "⚠️ CRITICAL: Medical Disclaimer & Legal Notice", 
    disclaimer_text: "ARTIFICIAL INTELLIGENCE IS NOT A DOCTOR\n\n🚨 EMERGENCY: If experiencing chest pain, difficulty breathing, severe injury, thoughts of self-harm, or any life-threatening emergency, CALL 911 (US) or your local emergency number IMMEDIATELY. Do not use this app.\n\n⚖️ LEGAL BINDING NOTICE:\nThis application provides general health information ONLY. It is NOT a substitute for, and does NOT replace, professional medical advice, diagnosis, physical examination, or treatment by a licensed healthcare provider.\n\nWARNINGS:\n• NO WARRANTY: This application is provided \"as-is\" with NO guarantees of accuracy, completeness, or fitness for any medical purpose\n• NEVER rely on this AI for diagnosis, treatment decisions, or medication advice\n• AI may produce incorrect, incomplete, or dangerous medical information\n• Your medical history, context, and individual factors cannot be fully assessed by AI\n• Delaying professional medical care due to AI advice can result in serious harm or death\n\nYOU ARE RESPONSIBLE FOR:\n• Verifying all information with a licensed healthcare provider\n• Seeking immediate professional medical attention for any health concern\n• Disclosing all symptoms, medications, and medical history to your doctor\n• Understanding that self-diagnosis via AI is unreliable and potentially dangerous\n\nWe strongly recommend consulting with a licensed physician, nurse, or qualified healthcare professional for ANY medical concern. Your health and life depend on professional medical judgment.",
    disclaimer_accept: "I Understand", 
    settings_title: "Settings", 
    status_checking: "Checking…", 
    status_online: "Online", 
    status_offline: "Offline", 
    input_placeholder: "Describe symptoms, ask a health question, or upload a photo…", 
    welcome_title: "Gemma Health Edge", 
    welcome_subtitle: "Advanced Offline Medical Intelligence Dashboard", 
    settings_thinking: "Show Thinking", 
    toast_copied: "Copied!", 
    toast_saved: "Saved!", 
    toast_error: "Error occurred", 
    thinking: "Thinking…",
    newSession: "New Session",
    serverOnline: "Online",
    serverOffline: "Offline",
    autoDetect: "Auto-detect",
    calendarTitle: "Health Calendar",
    moodLabel: "Mood",
    moodAverage: "Avg this month",
    cameraButton: "Camera",
    galleryButton: "Gallery",
    researchNote: "🔬 Wikipedia context added",
    notADoctor: "I'm not a doctor. Always consult a healthcare professional.",
    sessionHistory: "Session History",
    clearChat: "Clear",
    help: "Help",
    btn_clear_chat: "Clear",
    copyMessage: "Copy",
    exportChat: "Export Chat",
    privacyBadge: "100% Private",
    healthSector: "Health Sector",
    moodQuestion: "How are you feeling today?",
    moodNotePlaceholder: "Add a note (optional)...",
    medicalDisclaimer: "⚠️ MEDICAL DISCLAIMER",
    disclaimerText: "ARTIFICIAL INTELLIGENCE IS NOT A DOCTOR. This assistant provides general information only and is NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult a licensed healthcare provider. In emergencies, call 911 immediately.",
    hwHardware: "Hardware",
    hwVRAM: "VRAM",
    hwAcceleration: "Acceleration",
    hwTTFT: "TTFT",
    hwTPS: "TPS",
    hwTotalTime: "TOTAL TIME",
    hwPrivacyMode: "Privacy Mode",
    hwPrivacyValue: "100% Offline",
    cardSymptomChecker: "Symptom Checker",
    cardSymptomDesc: "Headache and mild fever",
    cardMedicationInfo: "Medication Info",
    cardMedicationDesc: "Side effects of Ibuprofen",
    cardWellnessTips: "Wellness Tips",
    cardWellnessDesc: "Improve sleep schedule",
    cardHealthMetrics: "Health Metrics",
    cardHealthDesc: "Normal blood pressure",
    cardNutrition: "Nutrition",
    cardNutritionDesc: "Healthy diet advice",
    cardMentalHealth: "Mental Health",
    cardMentalDesc: "Stress management",
    cardFitnessPlan: "Fitness Plan",
    cardFitnessDesc: "Home workout routines",
    cardFirstAid: "First Aid",
    cardFirstAidDesc: "Treating minor burns",
    cardVaccinations: "Vaccinations",
    cardVaccinationsDesc: "Adult immunization schedule",
    cardLabResults: "Lab Results",
    cardLabResultsDesc: "Understanding blood tests",
    help_title: "🚀 Quick Start Guide",
    help_step1: "Just start typing! Describe your symptoms or ask a health question in the box at the bottom.",
    help_step2: "AI is not a doctor. We provide information, not medical advice. Always consult a professional.",
    help_step3: "Privacy First. Your data stays on your computer. Look for the 100% Private badge.",
    help_step4: "Emergency? If you have severe symptoms, call 911 or your local emergency number immediately.",
    help_got_it: "Got it!",
    tab_server: "Server",
    tab_customization: "Customization",
    tab_language: "Language",
    tab_features: "Features",
    tab_clinical: "My Clinical Profile",
    tab_troubleshooting: "Troubleshooting",
    server_config_title: "Server Configuration",
    server_config_desc: "Configure your AI backend connection",
    custom_title: "Customization",
    custom_desc: "Personalize your interface appearance",
    lang_title: "Language",
    lang_desc: "Select your preferred language",
    features_title: "Features",
    features_desc: "Enable or disable additional features",
    clinical_title: "My Clinical Profile",
    clinical_desc: "Your medical information helps the AI provide personalized advice",
    trouble_title: "Troubleshooting",
    trouble_desc: "Diagnostic tools and common issue fixes",
    label_ai_backend: "AI Backend",
    label_gemma_key: "Gemma API Key",
    label_openrouter_key: "OpenRouter Key",
    label_theme: "Theme",
    label_research: "Research Mode (Wikipedia when online)",
    label_camera: "Enable Camera Button",
    label_voice: "Read Responses Aloud (TTS)",
    label_allergies: "Allergies",
    label_conditions: "Medical Conditions",
    label_medications: "Current Medications",
    label_age: "Age",
    label_weight: "Weight (kg)",
    label_notes: "Additional Notes",
    hint_allergies: "List all known allergies, separated by commas",
    hint_conditions: "Chronic conditions or ongoing health issues",
    hint_medications: "Include dosages if known. This helps avoid drug interaction warnings.",
    btn_save_profile: "Save Profile",
    trouble_diag_title: "Connection Diagnostics",
    trouble_sys_title: "System Information",
    trouble_faq_title: "Common Issues",
    clinical_disclaimer: "This data is stored locally on your device and sent with chat requests to personalize AI responses.",
    privacy_badge_text: "100% Local & Encrypted",
    history_label: "Chats",
    search_title: "Search Sessions",
    camera_take: "Take a Photo",
    camera_cancel: "Cancel",
    camera_capture: "Capture",
    mood_note_placeholder: "Add a note (optional)...",
    faq_slow: "AI responses are slow or timing out",
    faq_pdf: "PDF import is not working",
    faq_camera: "Camera button not appearing",
    faq_lang: "Language not changing",
  },
  fr: { 
    appTitle: "Gemma Health Edge",
    disclaimer_title: "⚠️ AVERTISSEMENT MÉDICAL CRITIQUE", 
    disclaimer_text: "L'INTELLIGENCE ARTIFICIELLE N'EST PAS UN MÉDECIN\n\n🚨 URGENCE: En cas de douleur thoracique, difficultés respiratoires, blessure grave, idées suicidaires ou urgence menaçant la vie, APPELEZ LE 15 (SAMU) ou vos services d'urgence IMMÉDIATEMENT.\n\n⚖️ AVIS JURIDIQUE CONTRAIGNANT:\nCette application fournit UNIQUEMENT des informations de santé générales. Elle ne remplace PAS les conseils, le diagnostic ou le traitement d'un professionnel de santé agréé.\n\nAVERTISSEMENTS:\n• AUCUNE GARANTIE: Cette application est fournie \"telle quelle\" sans garantie d'exactitude ou d'adéquation\n• Ne vous fiez JAMAIS à cette IA pour diagnostiquer, traiter ou prescrire\n• L'IA peut produire des informations médicales incorrectes ou dangereuses\n• Votre historique médical ne peut pas être pleinement évalué par l'IA\n• Retarder les soins médicaux professionnels peut avoir des conséquences graves ou mortelles\n\nVous êtes RESPONSABLE de:\n• Vérifier toute information auprès d'un professionnel de santé agréé\n• Consulter immédiatement un médecin pour toute préoccupation de santé\n• Révéler tous vos symptômes et antécédents médicaux à votre médecin\n\nConsultez toujours un médecin agréé pour tout problème de santé.",
    disclaimer_accept: "Je Comprends", 
    settings_title: "Paramètres",
    status_checking: "Vérification…",
    status_online: "En ligne",
    status_offline: "Hors ligne",
    input_placeholder: "Décrivez les symptômes...",
    welcome_title: "Gemma Health Edge",
    welcome_subtitle: "Tableau de bord intelligent médical hors ligne",
    settings_thinking: "Afficher la réflexion",
    toast_copied: "Copié !",
    toast_saved: "Enregistré !",
    toast_error: "Erreur",
    thinking: "Réflexion…",
    newSession: "Nouveau chat",
    serverOnline: "Connecté",
    serverOffline: "Déconnecté",
    autoDetect: "Détection auto",
    calendarTitle: "Calendrier santé",
    moodLabel: "Humeur",
    moodAverage: "Moy. ce mois",
    cameraButton: "Appareil photo",
    galleryButton: "Galerie",
    researchNote: "🔬 Contexte Wiki ajouté",
    notADoctor: "Je ne suis pas médecin. Consultez toujours un professionnel de santé.",
    sessionHistory: "Rechercher",
    clearChat: "Effacer",
    help: "Aide",
    btn_clear_chat: "Effacer",
    copyMessage: "Copier",
    exportChat: "Exporter",
    privacyBadge: "100 % Privé",
    healthSector: "Secteur santé",
    moodQuestion: "Comment vous sentez-vous aujourd'hui ?",
    moodNotePlaceholder: "Ajouter une note (optionnel)...",
    medicalDisclaimer: "⚠️ AVERTISSEMENT MÉDICAL",
    disclaimerText: "L'INTELLIGENCE ARTIFICIELLE N'EST PAS UN MÉDECIN. Cet assistant fournit uniquement des informations générales et ne remplace PAS l'avis médical professionnel, le diagnostic ou le traitement. Consultez toujours un professionnel de santé agréé. En cas d'urgence, appelez le 15 (SAMU) immédiatement.",
    hwHardware: "Matériel",
    hwVRAM: "VRAM",
    hwAcceleration: "Accélération",
    hwTTFT: "TTFT",
    hwTPS: "TPS",
    hwTotalTime: "TEMPS TOTAL",
    hwPrivacyMode: "Mode privé",
    hwPrivacyValue: "100 % hors ligne",
    cardSymptomChecker: "Vérif. de symptômes",
    cardSymptomDesc: "Mal de tête et fièvre légère",
    cardMedicationInfo: "Info médicaments",
    cardMedicationDesc: "Effets secondaires Ibuprofène",
    cardWellnessTips: "Conseils bien-être",
    cardWellnessDesc: "Améliorer le sommeil",
    cardHealthMetrics: "Indicateurs santé",
    cardHealthDesc: "Tension artérielle normale",
    cardNutrition: "Nutrition",
    cardNutritionDesc: "Conseils alimentation saine",
    cardMentalHealth: "Santé mentale",
    cardMentalDesc: "Gestion du stress",
    cardFitnessPlan: "Plan fitness",
    cardFitnessDesc: "Exercices à la maison",
    cardFirstAid: "Premiers secours",
    cardFirstAidDesc: "Soigner brûlures légères",
    cardVaccinations: "Vaccinations",
    cardVaccinationsDesc: "Calendrier vaccinal adulte",
    cardLabResults: "Résultats d'analyses",
    cardLabResultsDesc: "Comprendre tests sanguins",
    help_title: "🚀 Quick Start Guide",
    help_step1: "Just start typing! Describe your symptoms or ask a health question in the box at the bottom.",
    help_step2: "AI is not a doctor. We provide information, not medical advice. Always consult a professional.",
    help_step3: "Privacy First. Your data stays on your computer. Look for the 100% Private badge.",
    help_step4: "Emergency? If you have severe symptoms, call 911 or your local emergency number immediately.",
    help_got_it: "Got it!",
    tab_server: "Server",
    tab_customization: "Customization",
    tab_language: "Language",
    tab_features: "Features",
    tab_clinical: "My Clinical Profile",
    tab_troubleshooting: "Troubleshooting",
    server_config_title: "Server Configuration",
    server_config_desc: "Configure your AI backend connection",
    custom_title: "Customization",
    custom_desc: "Personalize your interface appearance",
    lang_title: "Language",
    lang_desc: "Select your preferred language",
    features_title: "Features",
    features_desc: "Enable or disable additional features",
    clinical_title: "My Clinical Profile",
    clinical_desc: "Your medical information helps the AI provide personalized advice",
    trouble_title: "Troubleshooting",
    trouble_desc: "Diagnostic tools and common issue fixes",
    label_ai_backend: "AI Backend",
    label_gemma_key: "Gemma API Key",
    label_openrouter_key: "OpenRouter Key",
    label_theme: "Theme",
    label_research: "Research Mode (Wikipedia when online)",
    label_camera: "Enable Camera Button",
    label_voice: "Read Responses Aloud (TTS)",
    label_allergies: "Allergies",
    label_conditions: "Medical Conditions",
    label_medications: "Current Medications",
    label_age: "Age",
    label_weight: "Weight (kg)",
    label_notes: "Additional Notes",
    hint_allergies: "List all known allergies, separated by commas",
    hint_conditions: "Chronic conditions or ongoing health issues",
    hint_medications: "Include dosages if known. This helps avoid drug interaction warnings.",
    btn_save_profile: "Save Profile",
    trouble_diag_title: "Connection Diagnostics",
    trouble_sys_title: "System Information",
    trouble_faq_title: "Common Issues",
    clinical_disclaimer: "This data is stored locally on your device and sent with chat requests to personalize AI responses.",
    privacy_badge_text: "100% Local & Encrypted",
    history_label: "Conversations",
    search_title: "Search Sessions",
    camera_take: "Take a Photo",
    camera_cancel: "Cancel",
    camera_capture: "Capture",
    mood_note_placeholder: "Add a note (optional)...",
    faq_slow: "AI responses are slow or timing out",
    faq_pdf: "PDF import is not working",
    faq_camera: "Camera button not appearing",
    faq_lang: "Language not changing",
  },
  de: { 
    appTitle: "Gemma Health Edge",
    disclaimer_title: "⚠️ KRITISCHER MEDIZINISCHER HAFTUNGSAUSSCHLUSS", 
    disclaimer_text: "KÜNSTLICHE INTELLIGENZ IST KEIN ARZT\n\n🚨 NOTFALL: Bei Brustschmerzen, Atemwegsbehinderung, schweren Verletzungen, Selbstmordgedanken oder lebensbedrohlichen Notfällen SOFORT den Rettungsdienst (112) anrufen. Diese App nicht verwenden.\n\n⚖️ RECHTLICHE BINDENDE MITTEILUNG:\nDiese Anwendung bietet NUR allgemeine Gesundheitsinformationen. Sie ersetzt NICHT die fachliche medizinische Beratung, Diagnose oder Behandlung durch einen lizenzierten Gesundheitsdienstleister.\n\nWARNUNGEN:\n• KEINE GARANTIE: Diese Anwendung wird „wie vorhanden\" bereitgestellt OHNE Garantien für Genauigkeit oder medizinische Eignung\n• Verlassen Sie sich NIEMALS auf diese KI zur Diagnose, Behandlung oder Verschreibung\n• Die KI kann falsche oder gefährliche medizinische Informationen produzieren\n• Ihre medizinische Geschichte kann von der KI nicht vollständig bewertet werden\n• Das Verzögern professioneller medizinischer Versorgung kann schwerwiegende Folgen haben oder tödlich sein\n\nSIE SIND VERANTWORTLICH FÜR:\n• Überprüfung aller Informationen bei einem lizenzierten Gesundheitsdienstleister\n• Sofortige Konsultation eines Arztes für alle Gesundheitsbedenken\n• Offenlegung aller Symptome und medizinischen Vorgeschichte gegenüber Ihrem Arzt\n\nKonsultieren Sie immer einen lizenzierten Arzt für alle Gesundheitsprobleme.", 
    disclaimer_accept: "Ich verstehe", 
    settings_title: "Einstellungen",
    status_checking: "Prüfung…",
    status_online: "Online",
    status_offline: "Offline",
    input_placeholder: "Symptome beschreiben...",
    welcome_title: "Gemma Health Edge",
    welcome_subtitle: "Erweitertes Offline-Dashboard für medizinische Intelligenz",
    settings_thinking: "Denkvorgang anzeigen",
    toast_copied: "Kopiert!",
    toast_saved: "Gespeichert!",
    toast_error: "Fehler",
    thinking: "Denkt nach…",
    newSession: "Neuer Chat",
    serverOnline: "Online",
    serverOffline: "Offline",
    autoDetect: "Auto-Erkennung",
    calendarTitle: "Gesundheitskalender",
    moodLabel: "Stimmung",
    moodAverage: "Schnitt diesen Monat",
    cameraButton: "Kamera",
    galleryButton: "Galerie",
    researchNote: "🔬 Wiki-Kontext hinzugefügt",
    notADoctor: "Ich bin kein Arzt. Konsultieren Sie immer einen Facharzt.",
    sessionHistory: "Suchen",
    clearChat: "Löschen",
    help: "Hilfe",
    btn_clear_chat: "Löschen",
    copyMessage: "Kopieren",
    exportChat: "Exportieren",
    privacyBadge: "100 % Privat",
    healthSector: "Gesundheitssektor",
    moodQuestion: "Wie fühlen Sie sich heute?",
    moodNotePlaceholder: "Notiz hinzufügen (optional)...",
    medicalDisclaimer: "⚠️ MEDIZINISCHER HAFTUNGSAUSSCHLUSS",
    disclaimerText: "KÜNSTLICHE INTELLIGENZ IST KEIN ARZT. Dieser Assistent bietet nur allgemeine Informationen und ist KEIN Ersatz für professionelle medizinische Beratung, Diagnose oder Behandlung. Konsultieren Sie immer einen lizenzierten Arzt. Rufen Sie im Notfall sofort 112 an.",
    hwHardware: "Hardware",
    hwVRAM: "VRAM",
    hwAcceleration: "Beschleunigung",
    hwTTFT: "TTFT",
    hwTPS: "TPS",
    hwTotalTime: "GESAMTZEIT",
    hwPrivacyMode: "Privatsphärenmodus",
    hwPrivacyValue: "100 % Offline",
    cardSymptomChecker: "Symptom-Checker",
    cardSymptomDesc: "Kopfschmerzen und leichtes Fieber",
    cardMedicationInfo: "Medikamenteninfo",
    cardMedicationDesc: "Nebenwirkungen von Ibuprofen",
    cardWellnessTips: "Wellness-Tipps",
    cardWellnessDesc: "Schlaf verbessern",
    cardHealthMetrics: "Gesundheitswerte",
    cardHealthDesc: "Normaler Blutdruck",
    cardNutrition: "Ernährung",
    cardNutritionDesc: "Gesunde Ernährungstipps",
    cardMentalHealth: "Psychische Gesundheit",
    cardMentalDesc: "Stressbewältigung",
    cardFitnessPlan: "Fitnessplan",
    cardFitnessDesc: "Heimworkout-Routinen",
    cardFirstAid: "Erste Hilfe",
    cardFirstAidDesc: "Behandlung kleiner Verbrennungen",
    cardVaccinations: "Impfungen",
    cardVaccinationsDesc: "Erwachsenen-Impfplan",
    cardLabResults: "Laborergebnisse",
    cardLabResultsDesc: "Bluttests verstehen",
    help_title: "🚀 Quick Start Guide",
    help_step1: "Just start typing! Describe your symptoms or ask a health question in the box at the bottom.",
    help_step2: "AI is not a doctor. We provide information, not medical advice. Always consult a professional.",
    help_step3: "Privacy First. Your data stays on your computer. Look for the 100% Private badge.",
    help_step4: "Emergency? If you have severe symptoms, call 911 or your local emergency number immediately.",
    help_got_it: "Got it!",
    tab_server: "Server",
    tab_customization: "Customization",
    tab_language: "Language",
    tab_features: "Features",
    tab_clinical: "My Clinical Profile",
    tab_troubleshooting: "Troubleshooting",
    server_config_title: "Server Configuration",
    server_config_desc: "Configure your AI backend connection",
    custom_title: "Customization",
    custom_desc: "Personalize your interface appearance",
    lang_title: "Language",
    lang_desc: "Select your preferred language",
    features_title: "Features",
    features_desc: "Enable or disable additional features",
    clinical_title: "My Clinical Profile",
    clinical_desc: "Your medical information helps the AI provide personalized advice",
    trouble_title: "Troubleshooting",
    trouble_desc: "Diagnostic tools and common issue fixes",
    label_ai_backend: "AI Backend",
    label_gemma_key: "Gemma API Key",
    label_openrouter_key: "OpenRouter Key",
    label_theme: "Theme",
    label_research: "Research Mode (Wikipedia when online)",
    label_camera: "Enable Camera Button",
    label_voice: "Read Responses Aloud (TTS)",
    label_allergies: "Allergies",
    label_conditions: "Medical Conditions",
    label_medications: "Current Medications",
    label_age: "Age",
    label_weight: "Weight (kg)",
    label_notes: "Additional Notes",
    hint_allergies: "List all known allergies, separated by commas",
    hint_conditions: "Chronic conditions or ongoing health issues",
    hint_medications: "Include dosages if known. This helps avoid drug interaction warnings.",
    btn_save_profile: "Save Profile",
    trouble_diag_title: "Connection Diagnostics",
    trouble_sys_title: "System Information",
    trouble_faq_title: "Common Issues",
    clinical_disclaimer: "This data is stored locally on your device and sent with chat requests to personalize AI responses.",
    privacy_badge_text: "100% Local & Encrypted",
    history_label: "Chats",
    search_title: "Search Sessions",
    camera_take: "Take a Photo",
    camera_cancel: "Cancel",
    camera_capture: "Capture",
    mood_note_placeholder: "Add a note (optional)...",
    faq_slow: "AI responses are slow or timing out",
    faq_pdf: "PDF import is not working",
    faq_camera: "Camera button not appearing",
    faq_lang: "Language not changing",
  },
  es: { 
    appTitle: "Gemma Health Edge",
    disclaimer_title: "⚠️ DESCARGO CRÍTICO DE RESPONSABILIDAD MÉDICA", 
    disclaimer_text: "LA INTELIGENCIA ARTIFICIAL NO ES UN MÉDICO\n\n🚨 EMERGENCIA: Si experimenta dolor en el pecho, dificultad para respirar, lesiones graves, pensamientos suicidas o cualquier emergencia que amenace la vida, LLAME AL 911 (EE.UU.) o al número de emergencia local INMEDIATAMENTE.\n\n⚖️ AVISO LEGAL VINCULANTE:\nEsta aplicación proporciona SOLO información general de salud. NO reemplaza y NO sustituye el consejo médico profesional, el diagnóstico o el tratamiento de un proveedor de atención médica con licencia.\n\nADVERTENCIAS:\n• SIN GARANTÍA: Esta aplicación se proporciona \"tal cual\" SIN garantías de exactitud o idoneidad médica\n• NUNCA confíe en esta IA para diagnóstico, tratamiento o medicamentos\n• La IA puede producir información médica incorrecta o peligrosa\n• Su historial médico no puede ser evaluado completamente por la IA\n• Retrasar la atención médica profesional puede resultar en daño grave o muerte\n\nUSTE ES RESPONSABLE DE:\n• Verificar toda la información con un proveedor de atención médica con licencia\n• Buscar atención médica profesional inmediata para cualquier preocupación de salud\n• Divulgar todos los síntomas e historial médico a su médico\n\nSiempre consulte con un médico con licencia para cualquier problema de salud.", 
    disclaimer_accept: "Entiendo", 
    settings_title: "Ajustes",
    status_checking: "Comprobando…",
    status_online: "En línea",
    status_offline: "Desconectado",
    input_placeholder: "Describa los síntomas...",
    welcome_title: "Gemma Health Edge",
    welcome_subtitle: "Panel de inteligencia médica avanzada fuera de línea",
    settings_thinking: "Mostrar pensamiento",
    toast_copied: "¡Copiado!",
    toast_saved: "¡Guardado!",
    toast_error: "Error",
    thinking: "Pensando…",
    newSession: "Nuevo chat",
    serverOnline: "Conectado",
    serverOffline: "Desconectado",
    autoDetect: "Auto-detectar",
    calendarTitle: "Calendario de salud",
    moodLabel: "Estado de ánimo",
    moodAverage: "Prom. este mes",
    cameraButton: "Cámara",
    galleryButton: "Galería",
    researchNote: "🔬 Contexto Wiki añadido",
    notADoctor: "No soy médico. Consulte siempre a un profesional sanitario.",
    sessionHistory: "Buscar",
    clearChat: "Limpiar",
    help: "Ayuda",
    btn_clear_chat: "Limpiar",
    copyMessage: "Copiar",
    exportChat: "Exportar",
    privacyBadge: "100 % Privado",
    healthSector: "Sector salud",
    moodQuestion: "¿Cómo se siente hoy?",
    moodNotePlaceholder: "Añadir nota (opcional)...",
    medicalDisclaimer: "⚠️ DESCARGO DE RESPONSABILIDAD MÉDICA",
    disclaimerText: "LA INTELIGENCIA ARTIFICIAL NO ES UN MÉDICO. Este asistente proporciona solo información general y NO es un sustituto de la asesoramiento médico profesional, diagnóstico o tratamiento. Siempre consulte a un proveedor de atención médica con licencia. En emergencias, llame al 911 inmediatamente.",
    hwHardware: "Hardware",
    hwVRAM: "VRAM",
    hwAcceleration: "Aceleración",
    hwTTFT: "TTFT",
    hwTPS: "TPS",
    hwTotalTime: "TIEMPO TOTAL",
    hwPrivacyMode: "Modo privado",
    hwPrivacyValue: "100 % Offline",
    cardSymptomChecker: "Verificador de síntomas",
    cardSymptomDesc: "Dolor de cabeza y fiebre leve",
    cardMedicationInfo: "Info medicamentos",
    cardMedicationDesc: "Efectos secundarios del Ibuprofeno",
    cardWellnessTips: "Consejos de bienestar",
    cardWellnessDesc: "Mejorar el sueño",
    cardHealthMetrics: "Métricas de salud",
    cardHealthDesc: "Presión arterial normal",
    cardNutrition: "Nutrición",
    cardNutritionDesc: "Consejos de alimentación saludable",
    cardMentalHealth: "Salud mental",
    cardMentalDesc: "Manejo del estrés",
    cardFitnessPlan: "Plan de fitness",
    cardFitnessDesc: "Rutinas de ejercicio en casa",
    cardFirstAid: "Primeros auxilios",
    cardFirstAidDesc: "Tratar quemaduras leves",
    cardVaccinations: "Vacunaciones",
    cardVaccinationsDesc: "Calendario de vacunación adulto",
    cardLabResults: "Resultados de laboratorio",
    cardLabResultsDesc: "Comprender análisis de sangre",
    help_title: "🚀 Quick Start Guide",
    help_step1: "Just start typing! Describe your symptoms or ask a health question in the box at the bottom.",
    help_step2: "AI is not a doctor. We provide information, not medical advice. Always consult a professional.",
    help_step3: "Privacy First. Your data stays on your computer. Look for the 100% Private badge.",
    help_step4: "Emergency? If you have severe symptoms, call 911 or your local emergency number immediately.",
    help_got_it: "Got it!",
    tab_server: "Server",
    tab_customization: "Customization",
    tab_language: "Language",
    tab_features: "Features",
    tab_clinical: "My Clinical Profile",
    tab_troubleshooting: "Troubleshooting",
    server_config_title: "Server Configuration",
    server_config_desc: "Configure your AI backend connection",
    custom_title: "Customization",
    custom_desc: "Personalize your interface appearance",
    lang_title: "Language",
    lang_desc: "Select your preferred language",
    features_title: "Features",
    features_desc: "Enable or disable additional features",
    clinical_title: "My Clinical Profile",
    clinical_desc: "Your medical information helps the AI provide personalized advice",
    trouble_title: "Troubleshooting",
    trouble_desc: "Diagnostic tools and common issue fixes",
    label_ai_backend: "AI Backend",
    label_gemma_key: "Gemma API Key",
    label_openrouter_key: "OpenRouter Key",
    label_theme: "Theme",
    label_research: "Research Mode (Wikipedia when online)",
    label_camera: "Enable Camera Button",
    label_voice: "Read Responses Aloud (TTS)",
    label_allergies: "Allergies",
    label_conditions: "Medical Conditions",
    label_medications: "Current Medications",
    label_age: "Age",
    label_weight: "Weight (kg)",
    label_notes: "Additional Notes",
    hint_allergies: "List all known allergies, separated by commas",
    hint_conditions: "Chronic conditions or ongoing health issues",
    hint_medications: "Include dosages if known. This helps avoid drug interaction warnings.",
    btn_save_profile: "Save Profile",
    trouble_diag_title: "Connection Diagnostics",
    trouble_sys_title: "System Information",
    trouble_faq_title: "Common Issues",
    clinical_disclaimer: "This data is stored locally on your device and sent with chat requests to personalize AI responses.",
    privacy_badge_text: "100% Local & Encrypted",
    history_label: "Conversaciones",
    search_title: "Search Sessions",
    camera_take: "Take a Photo",
    camera_cancel: "Cancel",
    camera_capture: "Capture",
    mood_note_placeholder: "Add a note (optional)...",
    faq_slow: "AI responses are slow or timing out",
    faq_pdf: "PDF import is not working",
    faq_camera: "Camera button not appearing",
    faq_lang: "Language not changing",
  },
  zh: { 
    appTitle: "Gemma Health Edge",
    disclaimer_title: "医疗免责声明", 
    disclaimer_text: "此人工智能健康助手仅提供教育信息...", 
    disclaimer_accept: "我理解", 
    settings_title: "设置",
    status_checking: "正在检查…",
    status_online: "在线",
    status_offline: "离线",
    input_placeholder: "描述症状...",
    welcome_title: "Gemma Health Edge",
    welcome_subtitle: "高级离线医疗智能仪表板",
    settings_thinking: "显示思考过程",
    toast_copied: "已复制！",
    toast_saved: "已保存！",
    toast_error: "出错了",
    thinking: "正在思考…",
    newSession: "新对话",
    serverOnline: "在线",
    serverOffline: "离线",
    autoDetect: "自动检测",
    calendarTitle: "健康日历",
    moodLabel: "情绪",
    moodAverage: "本月平均",
    cameraButton: "拍照",
    galleryButton: "相册",
    researchNote: "🔬 维基背景已添加",
    notADoctor: "我不是医生。请始终咨询专业医护人员。",
    sessionHistory: "搜索",
    clearChat: "清除",
    help: "帮助",
    btn_clear_chat: "清除",
    copyMessage: "复制",
    exportChat: "导出",
    privacyBadge: "100% 私密",
    healthSector: "健康领域",
    moodQuestion: "今天您感觉怎么样？",
    moodNotePlaceholder: "添加备注（可选）...",
    medicalDisclaimer: "Medical Disclaimer",
    disclaimerText: "This assistant provides information only. It is not a substitute for professional medical advice, diagnosis, or treatment.",
    hwHardware: "硬件",
    hwVRAM: "显存",
    hwAcceleration: "加速",
    hwTTFT: "TTFT",
    hwTPS: "TPS",
    hwTotalTime: "总时间",
    hwPrivacyMode: "隐私模式",
    hwPrivacyValue: "100% 离线",
    cardSymptomChecker: "症状检查",
    cardSymptomDesc: "头痛和轻微发烧",
    cardMedicationInfo: "药物信息",
    cardMedicationDesc: "布洛芬副作用",
    cardWellnessTips: "健康建议",
    cardWellnessDesc: "改善睡眠",
    cardHealthMetrics: "健康指标",
    cardHealthDesc: "正常血压",
    cardNutrition: "营养",
    cardNutritionDesc: "健康饮食建议",
    cardMentalHealth: "心理健康",
    cardMentalDesc: "压力管理",
    cardFitnessPlan: "健身计划",
    cardFitnessDesc: "家庭锻炼日程",
    cardFirstAid: "急救",
    cardFirstAidDesc: "处理轻微烧伤",
    cardVaccinations: "接种疫苗",
    cardVaccinationsDesc: "成人接种时间表",
    cardLabResults: "化验结果",
    cardLabResultsDesc: "理解血液检查",
    help_title: "🚀 Quick Start Guide",
    help_step1: "Just start typing! Describe your symptoms or ask a health question in the box at the bottom.",
    help_step2: "AI is not a doctor. We provide information, not medical advice. Always consult a professional.",
    help_step3: "Privacy First. Your data stays on your computer. Look for the 100% Private badge.",
    help_step4: "Emergency? If you have severe symptoms, call 911 or your local emergency number immediately.",
    help_got_it: "Got it!",
    tab_server: "Server",
    tab_customization: "Customization",
    tab_language: "Language",
    tab_features: "Features",
    tab_clinical: "My Clinical Profile",
    tab_troubleshooting: "Troubleshooting",
    server_config_title: "Server Configuration",
    server_config_desc: "Configure your AI backend connection",
    custom_title: "Customization",
    custom_desc: "Personalize your interface appearance",
    lang_title: "Language",
    lang_desc: "Select your preferred language",
    features_title: "Features",
    features_desc: "Enable or disable additional features",
    clinical_title: "My Clinical Profile",
    clinical_desc: "Your medical information helps the AI provide personalized advice",
    trouble_title: "Troubleshooting",
    trouble_desc: "Diagnostic tools and common issue fixes",
    label_ai_backend: "AI Backend",
    label_gemma_key: "Gemma API Key",
    label_openrouter_key: "OpenRouter Key",
    label_theme: "Theme",
    label_research: "Research Mode (Wikipedia when online)",
    label_camera: "Enable Camera Button",
    label_voice: "Read Responses Aloud (TTS)",
    label_allergies: "Allergies",
    label_conditions: "Medical Conditions",
    label_medications: "Current Medications",
    label_age: "Age",
    label_weight: "Weight (kg)",
    label_notes: "Additional Notes",
    hint_allergies: "List all known allergies, separated by commas",
    hint_conditions: "Chronic conditions or ongoing health issues",
    hint_medications: "Include dosages if known. This helps avoid drug interaction warnings.",
    btn_save_profile: "Save Profile",
    trouble_diag_title: "Connection Diagnostics",
    trouble_sys_title: "System Information",
    trouble_faq_title: "Common Issues",
    clinical_disclaimer: "This data is stored locally on your device and sent with chat requests to personalize AI responses.",
    privacy_badge_text: "100% Local & Encrypted",
    history_label: "聊天记录",
    search_title: "Search Sessions",
    camera_take: "Take a Photo",
    camera_cancel: "Cancel",
    camera_capture: "Capture",
    mood_note_placeholder: "Add a note (optional)...",
    faq_slow: "AI responses are slow or timing out",
    faq_pdf: "PDF import is not working",
    faq_camera: "Camera button not appearing",
    faq_lang: "Language not changing",
  },
  hi: { 
    appTitle: "Gemma Health Edge",
    disclaimer_title: "चिकित्सा अस्वीकरण", 
    disclaimer_text: "यह एआई स्वास्थ्य सहायक केवल शैक्षिक उद्देश्यों के लिए जानकारी प्रदान करता है...", 
    disclaimer_accept: "मैं समझता हूँ", 
    settings_title: "सेटिंग्स",
    status_checking: "जाँच हो रही है…",
    status_online: "ऑनलाइन",
    status_offline: "ऑफलाइन",
    input_placeholder: "लक्षणों का वर्णन करें...",
    welcome_title: "Gemma Health Edge",
    welcome_subtitle: "उन्नत ऑफ़लाइन चिकित्सा खुफिया डैशबोर्ड",
    settings_thinking: "सोच दिखाएं",
    toast_copied: "कपी हो गया!",
    toast_saved: "सही हो गया!",
    toast_error: "त्रुटि",
    thinking: "सोच रहा है…",
    newSession: "नई बातचीत",
    serverOnline: "ऑनलाइन",
    serverOffline: "ऑफलाइन",
    autoDetect: "स्वचालित पतलग",
    calendarTitle: "स्वास्थ्य कैलेंडर",
    moodLabel: "मनोद्शा",
    moodAverage: "इस महीने औसत",
    cameraButton: "कैमरा",
    galleryButton: "गैलरी",
    researchNote: "🔬 विकि संदर्भ जोड़ा गया",
    notADoctor: "मैं डाक्टर नहीं हूं। हमेशा किसी स्वास्थ्य पेशेवर से परामर्श करें।",
    sessionHistory: "खोजें",
    clearChat: "साफ करें",
    help: "सहायता",
    btn_clear_chat: "साफ करें",
    copyMessage: "कपी करें",
    exportChat: "निर्यात",
    privacyBadge: "100% निजी",
    healthSector: "स्वास्थ्य क्षेत्र",
    moodQuestion: "आज आप कैसा महसूस कर रहे हैं?",
    moodNotePlaceholder: "नोट जोड़ें (ऐच्छिक)...",
    medicalDisclaimer: "Medical Disclaimer",
    disclaimerText: "This assistant provides information only. It is not a substitute for professional medical advice, diagnosis, or treatment.",
    hwHardware: "हार्डवेयर",
    hwVRAM: "VRAM",
    hwAcceleration: "त्वरण",
    hwTTFT: "TTFT",
    hwTPS: "TPS",
    hwTotalTime: "कुल समय",
    hwPrivacyMode: "गोपनीयता मोड",
    hwPrivacyValue: "100% ऑफलाइन",
    cardSymptomChecker: "लक्षण परीक्षक",
    cardSymptomDesc: "सिरदर्द और हल्का बुखार",
    cardMedicationInfo: "दवा जानकारी",
    cardMedicationDesc: "आईबुप्रोफेन के दुष्प्रभाव",
    cardWellnessTips: "स्वस्थता टिप्स",
    cardWellnessDesc: "नींद में सुधार",
    cardHealthMetrics: "स्वास्थ्य मैट्रिक्स",
    cardHealthDesc: "सामान्य रक्तचाप",
    cardNutrition: "पोषण",
    cardNutritionDesc: "स्वस्थ आहार सलाह",
    cardMentalHealth: "मानसिक स्वास्थ्य",
    cardMentalDesc: "तनाव प्रबंधन",
    cardFitnessPlan: "फितनेस योजना",
    cardFitnessDesc: "घर पर व्यायाम रूटीन",
    cardFirstAid: "प्रथम चिकित्सा",
    cardFirstAidDesc: "हल्की जलन का इलाज",
    cardVaccinations: "टीकाकरण",
    cardVaccinationsDesc: "व्यस्क टीकाकरण अनुसूची",
    cardLabResults: "प्रयोगशाला परिणाम",
    cardLabResultsDesc: "रक्त परीक्षण समझना",
    help_title: "🚀 Quick Start Guide",
    help_step1: "Just start typing! Describe your symptoms or ask a health question in the box at the bottom.",
    help_step2: "AI is not a doctor. We provide information, not medical advice. Always consult a professional.",
    help_step3: "Privacy First. Your data stays on your computer. Look for the 100% Private badge.",
    help_step4: "Emergency? If you have severe symptoms, call 911 or your local emergency number immediately.",
    help_got_it: "Got it!",
    tab_server: "Server",
    tab_customization: "Customization",
    tab_language: "Language",
    tab_features: "Features",
    tab_clinical: "My Clinical Profile",
    tab_troubleshooting: "Troubleshooting",
    server_config_title: "Server Configuration",
    server_config_desc: "Configure your AI backend connection",
    custom_title: "Customization",
    custom_desc: "Personalize your interface appearance",
    lang_title: "Language",
    lang_desc: "Select your preferred language",
    features_title: "Features",
    features_desc: "Enable or disable additional features",
    clinical_title: "My Clinical Profile",
    clinical_desc: "Your medical information helps the AI provide personalized advice",
    trouble_title: "Troubleshooting",
    trouble_desc: "Diagnostic tools and common issue fixes",
    label_ai_backend: "AI Backend",
    label_gemma_key: "Gemma API Key",
    label_openrouter_key: "OpenRouter Key",
    label_theme: "Theme",
    label_research: "Research Mode (Wikipedia when online)",
    label_camera: "Enable Camera Button",
    label_voice: "Read Responses Aloud (TTS)",
    label_allergies: "Allergies",
    label_conditions: "Medical Conditions",
    label_medications: "Current Medications",
    label_age: "Age",
    label_weight: "Weight (kg)",
    label_notes: "Additional Notes",
    hint_allergies: "List all known allergies, separated by commas",
    hint_conditions: "Chronic conditions or ongoing health issues",
    hint_medications: "Include dosages if known. This helps avoid drug interaction warnings.",
    btn_save_profile: "Save Profile",
    trouble_diag_title: "Connection Diagnostics",
    trouble_sys_title: "System Information",
    trouble_faq_title: "Common Issues",
    clinical_disclaimer: "This data is stored locally on your device and sent with chat requests to personalize AI responses.",
    privacy_badge_text: "100% Local & Encrypted",
    history_label: "चैट इतिहास",
    search_title: "Search Sessions",
    camera_take: "Take a Photo",
    camera_cancel: "Cancel",
    camera_capture: "Capture",
    mood_note_placeholder: "Add a note (optional)...",
    faq_slow: "AI responses are slow or timing out",
    faq_pdf: "PDF import is not working",
    faq_camera: "Camera button not appearing",
    faq_lang: "Language not changing",
  },
  ru: { 
    appTitle: "Gemma Health Edge",
    disclaimer_title: "Отказ от медицинской ответственности", 
    disclaimer_text: "Этот медицинский ИИ-помощник предоставляет информацию только в образовательных целях...", 
    disclaimer_accept: "Я понимаю", 
    settings_title: "Настройки",
    status_checking: "Проверка…",
    status_online: "В сети",
    status_offline: "Не в сети",
    input_placeholder: "Опишите симптомы...",
    welcome_title: "Gemma Health Edge",
    welcome_subtitle: "Продвинутая оффлайн-панель медицинского интеллекта",
    settings_thinking: "Показать процесс мышления",
    toast_copied: "Скопировано!",
    toast_saved: "Сохранено!",
    toast_error: "Ошибка",
    thinking: "Думает…",
    newSession: "Новый чат",
    serverOnline: "Онлайн",
    serverOffline: "Оффлайн",
    autoDetect: "Автоопределение",
    calendarTitle: "Календарь здоровья",
    moodLabel: "Настроение",
    moodAverage: "Среднее за месяц",
    cameraButton: "Камера",
    galleryButton: "Галерея",
    researchNote: "🔬 Контекст Вики добавлен",
    notADoctor: "Я не врач. Всегда консультируйтесь с медицинским специалистом.",
    sessionHistory: "Поиск",
    clearChat: "Очистить",
    help: "Помощь",
    btn_clear_chat: "Очистить",
    copyMessage: "Копировать",
    exportChat: "Экспорт",
    privacyBadge: "100 % Конфиденциально",
    healthSector: "Сфера здоровья",
    moodQuestion: "Как вы себя чувствуете сегодня?",
    moodNotePlaceholder: "Добавить заметку (необязательно)...",
    medicalDisclaimer: "Medical Disclaimer",
    disclaimerText: "This assistant provides information only. It is not a substitute for professional medical advice, diagnosis, or treatment.",
    hwHardware: "Оборудование",
    hwVRAM: "Видеопамять",
    hwAcceleration: "Ускорение",
    hwTTFT: "TTFT",
    hwTPS: "TPS",
    hwTotalTime: "ОБЩЕЕ ВРЕМЯ",
    hwPrivacyMode: "Приватный режим",
    hwPrivacyValue: "100 % Оффлайн",
    cardSymptomChecker: "Проверка симптомов",
    cardSymptomDesc: "Головная боль и легкая температура",
    cardMedicationInfo: "Инфо о лекарствах",
    cardMedicationDesc: "Побочные эффекты Ибупрофена",
    cardWellnessTips: "Советы по благополучию",
    cardWellnessDesc: "Улучшить сон",
    cardHealthMetrics: "Показатели здоровья",
    cardHealthDesc: "Нормальное давление",
    cardNutrition: "Питание",
    cardNutritionDesc: "Советы по здоровому питанию",
    cardMentalHealth: "Психическое здоровье",
    cardMentalDesc: "Управление стрессом",
    cardFitnessPlan: "Фитнес-план",
    cardFitnessDesc: "Домашние тренировки",
    cardFirstAid: "Первая помощь",
    cardFirstAidDesc: "Лечение легких ожогов",
    cardVaccinations: "Вакцинации",
    cardVaccinationsDesc: "График вакцинации для взрослых",
    cardLabResults: "Результаты анализов",
    cardLabResultsDesc: "Понимание анализов крови",
    help_title: "🚀 Quick Start Guide",
    help_step1: "Just start typing! Describe your symptoms or ask a health question in the box at the bottom.",
    help_step2: "AI is not a doctor. We provide information, not medical advice. Always consult a professional.",
    help_step3: "Privacy First. Your data stays on your computer. Look for the 100% Private badge.",
    help_step4: "Emergency? If you have severe symptoms, call 911 or your local emergency number immediately.",
    help_got_it: "Got it!",
    tab_server: "Server",
    tab_customization: "Customization",
    tab_language: "Language",
    tab_features: "Features",
    tab_clinical: "My Clinical Profile",
    tab_troubleshooting: "Troubleshooting",
    server_config_title: "Server Configuration",
    server_config_desc: "Configure your AI backend connection",
    custom_title: "Customization",
    custom_desc: "Personalize your interface appearance",
    lang_title: "Language",
    lang_desc: "Select your preferred language",
    features_title: "Features",
    features_desc: "Enable or disable additional features",
    clinical_title: "My Clinical Profile",
    clinical_desc: "Your medical information helps the AI provide personalized advice",
    trouble_title: "Troubleshooting",
    trouble_desc: "Diagnostic tools and common issue fixes",
    label_ai_backend: "AI Backend",
    label_gemma_key: "Gemma API Key",
    label_openrouter_key: "OpenRouter Key",
    label_theme: "Theme",
    label_research: "Research Mode (Wikipedia when online)",
    label_camera: "Enable Camera Button",
    label_voice: "Read Responses Aloud (TTS)",
    label_allergies: "Allergies",
    label_conditions: "Medical Conditions",
    label_medications: "Current Medications",
    label_age: "Age",
    label_weight: "Weight (kg)",
    label_notes: "Additional Notes",
    hint_allergies: "List all known allergies, separated by commas",
    hint_conditions: "Chronic conditions or ongoing health issues",
    hint_medications: "Include dosages if known. This helps avoid drug interaction warnings.",
    btn_save_profile: "Save Profile",
    trouble_diag_title: "Connection Diagnostics",
    trouble_sys_title: "System Information",
    trouble_faq_title: "Common Issues",
    clinical_disclaimer: "This data is stored locally on your device and sent with chat requests to personalize AI responses.",
    privacy_badge_text: "100% Local & Encrypted",
    history_label: "Чаты",
    search_title: "Search Sessions",
    camera_take: "Take a Photo",
    camera_cancel: "Cancel",
    camera_capture: "Capture",
    mood_note_placeholder: "Add a note (optional)...",
    faq_slow: "AI responses are slow or timing out",
    faq_pdf: "PDF import is not working",
    faq_camera: "Camera button not appearing",
    faq_lang: "Language not changing",
  },
  mn: { 
    appTitle: "Gemma Health Edge",
    disclaimer_title: "Эмнэлгийн хариуцлагын татгалзал", 
    disclaimer_text: "Энэхүү AI эрүүл мэндийн туслаг зөвхөн боловсролын зорилгоор мэдээлэл өгдөг...", 
    disclaimer_accept: "Ойлголоо", 
    settings_title: "Тохиргоо",
    status_checking: "Шалгаж байна…",
    status_online: "Онлайн",
    status_offline: "Оффлайн",
    input_placeholder: "Шинж тэмдгийг тайлбарлах...",
    welcome_title: "Gemma Health Edge",
    welcome_subtitle: "Дэвшилтэй офлайн эмнэлгийн ухаалагийн самбар",
    settings_thinking: "Бодол харуулах",
    toast_copied: "Хуулагдсан!",
    toast_saved: "Хадгалагдсан!",
    toast_error: "Алдага",
    thinking: "Бодож байна…",
    newSession: "Шинэ чат",
    serverOnline: "Онлайн",
    serverOffline: "Оффлайн",
    autoDetect: "Авто илрүүлэх",
    calendarTitle: "Эрүүл мэндийн хуанли",
    moodLabel: "Сетгэл бадал",
    moodAverage: "Энэ сарын дундаж",
    cameraButton: "Камера",
    galleryButton: "Галерей",
    researchNote: "🔬 Вики контекст нэмэгдсэн",
    notADoctor: "Би эмч биш. Эрүүл мэндийн мэргэжлтэнд үргэлж үнэлгүүлэх.",
    sessionHistory: "Хайх",
    clearChat: "Арилгах",
    help: "Тусламж",
    btn_clear_chat: "Арилгах",
    copyMessage: "Хуулах",
    exportChat: "Экспорт",
    privacyBadge: "100% Нийлийн",
    healthSector: "Эрүүл мэндийн салбар",
    moodQuestion: "Та өнөөдөр яаж байна вэ?",
    moodNotePlaceholder: "Тэмдэглэл нэмэх (сунгалтай)...",
    medicalDisclaimer: "Medical Disclaimer",
    disclaimerText: "This assistant provides information only. It is not a substitute for professional medical advice, diagnosis, or treatment.",
    hwHardware: "Тоног төхөөрөмж",
    hwVRAM: "VRAM",
    hwAcceleration: "Хурдацгалт",
    hwTTFT: "TTFT",
    hwTPS: "TPS",
    hwTotalTime: "НИЙТ ЦАГ",
    hwPrivacyMode: "Нийлийн горим",
    hwPrivacyValue: "100% Оффлайн",
    cardSymptomChecker: "Шинжик шалгуур",
    cardSymptomDesc: "Толгой өвдөх ба хөнгөн халуур",
    cardMedicationInfo: "Эм мэдээлэл",
    cardMedicationDesc: "Ибупрофены гаж нөлөө",
    cardWellnessTips: "Эрүүл мэндийн зөвлөгөө",
    cardWellnessDesc: "Нойроо сайжруулах",
    cardHealthMetrics: "Эрүүл мэндийн үзүүлэлт",
    cardHealthDesc: "Хэв цусны даралт хэв",
    cardNutrition: "Тэжээл",
    cardNutritionDesc: "Эрүүл хооллох зөвлөгөө",
    cardMentalHealth: "Сэтгэл зүй",
    cardMentalDesc: "Стрессын менежмент",
    cardFitnessPlan: "Фитнес төлөвлөгөө",
    cardFitnessDesc: "Гэрийн дахь дасал",
    cardFirstAid: "Юрэн тусламж",
    cardFirstAidDesc: "Хөнгөн түлэгдсоны эмчилгээ",
    cardVaccinations: "ДараалТоо",
    cardVaccinationsDesc: "Насбилчид зориулсан дараалтын хуваарь",
    cardLabResults: "Лабораторийн үр дүн",
    cardLabResultsDesc: "Цусны шинжилгээг ойлгох",
    help_title: "🚀 Quick Start Guide",
    help_step1: "Just start typing! Describe your symptoms or ask a health question in the box at the bottom.",
    help_step2: "AI is not a doctor. We provide information, not medical advice. Always consult a professional.",
    help_step3: "Privacy First. Your data stays on your computer. Look for the 100% Private badge.",
    help_step4: "Emergency? If you have severe symptoms, call 911 or your local emergency number immediately.",
    help_got_it: "Got it!",
    tab_server: "Server",
    tab_customization: "Customization",
    tab_language: "Language",
    tab_features: "Features",
    tab_clinical: "My Clinical Profile",
    tab_troubleshooting: "Troubleshooting",
    server_config_title: "Server Configuration",
    server_config_desc: "Configure your AI backend connection",
    custom_title: "Customization",
    custom_desc: "Personalize your interface appearance",
    lang_title: "Language",
    lang_desc: "Select your preferred language",
    features_title: "Features",
    features_desc: "Enable or disable additional features",
    clinical_title: "My Clinical Profile",
    clinical_desc: "Your medical information helps the AI provide personalized advice",
    trouble_title: "Troubleshooting",
    trouble_desc: "Diagnostic tools and common issue fixes",
    label_ai_backend: "AI Backend",
    label_gemma_key: "Gemma API Key",
    label_openrouter_key: "OpenRouter Key",
    label_theme: "Theme",
    label_research: "Research Mode (Wikipedia when online)",
    label_camera: "Enable Camera Button",
    label_voice: "Read Responses Aloud (TTS)",
    label_allergies: "Allergies",
    label_conditions: "Medical Conditions",
    label_medications: "Current Medications",
    label_age: "Age",
    label_weight: "Weight (kg)",
    label_notes: "Additional Notes",
    hint_allergies: "List all known allergies, separated by commas",
    hint_conditions: "Chronic conditions or ongoing health issues",
    hint_medications: "Include dosages if known. This helps avoid drug interaction warnings.",
    btn_save_profile: "Save Profile",
    trouble_diag_title: "Connection Diagnostics",
    trouble_sys_title: "System Information",
    trouble_faq_title: "Common Issues",
    clinical_disclaimer: "This data is stored locally on your device and sent with chat requests to personalize AI responses.",
    privacy_badge_text: "100% Local & Encrypted",
    history_label: "Чатууд",
    search_title: "Search Sessions",
    camera_take: "Take a Photo",
    camera_cancel: "Cancel",
    camera_capture: "Capture",
    mood_note_placeholder: "Add a note (optional)...",
    faq_slow: "AI responses are slow or timing out",
    faq_pdf: "PDF import is not working",
    faq_camera: "Camera button not appearing",
    faq_lang: "Language not changing",
  },
  ja: { 
    appTitle: "Gemma Health Edge",
    disclaimer_title: "免責事項", 
    disclaimer_text: "このAIヘルスアシスタントは教育目的の情報のみを提供します...", 
    disclaimer_accept: "理解しました", 
    settings_title: "設定",
    status_checking: "確認中…",
    status_online: "オンライン",
    status_offline: "オフライン",
    input_placeholder: "症状を説明してください...",
    welcome_title: "Gemma Health Edge",
    welcome_subtitle: "高度なオフライン医療インテリジェンスダッシュボード",
    settings_thinking: "思考を表示",
    toast_copied: "コピーしました!",
    toast_saved: "保存しました!",
    toast_error: "エラー",
    thinking: "考え中…",
    newSession: "新しいチャット",
    serverOnline: "オンライン",
    serverOffline: "オフライン",
    autoDetect: "自動認識",
    calendarTitle: "健康カレンダー",
    moodLabel: "気分",
    moodAverage: "今月の平均",
    cameraButton: "カメラ",
    galleryButton: "ギャラリー",
    researchNote: "🔬 ウィキ背景を追加しました",
    notADoctor: "私は医者ではありません。必ず医療専門家に相談してください。",
    sessionHistory: "検索",
    clearChat: "クリア",
    help: "ヘルプ",
    btn_clear_chat: "クリア",
    copyMessage: "コピー",
    exportChat: "エクスポート",
    privacyBadge: "100% プライバート",
    healthSector: "ヘルスケアセクター",
    moodQuestion: "今日のお気持ちはいかがですか？",
    moodNotePlaceholder: "ノートを追加（任意）...",
    medicalDisclaimer: "Medical Disclaimer",
    disclaimerText: "This assistant provides information only. It is not a substitute for professional medical advice, diagnosis, or treatment.",
    hwHardware: "ハードウェア",
    hwVRAM: "VRAM",
    hwAcceleration: "加速",
    hwTTFT: "TTFT",
    hwTPS: "TPS",
    hwTotalTime: "総時間",
    hwPrivacyMode: "プライバシーモード",
    hwPrivacyValue: "100% オフライン",
    cardSymptomChecker: "症状チェッカー",
    cardSymptomDesc: "頭痛と軽微な発熱",
    cardMedicationInfo: "薬の情報",
    cardMedicationDesc: "イブプロフェンの副作用",
    cardWellnessTips: "ウェルネスチップ",
    cardWellnessDesc: "睡眠の改善",
    cardHealthMetrics: "健康メトリクス",
    cardHealthDesc: "正常な血圧",
    cardNutrition: "栄養",
    cardNutritionDesc: "健康的な食事アドバイス",
    cardMentalHealth: "メンタルヘルス",
    cardMentalDesc: "ストレス管理",
    cardFitnessPlan: "フィットネス計画",
    cardFitnessDesc: "ホームワークアウト",
    cardFirstAid: "応急処置",
    cardFirstAidDesc: "軽度の火傷の処置",
    cardVaccinations: "接種",
    cardVaccinationsDesc: "大人の接種スケジュール",
    cardLabResults: "検査結果",
    cardLabResultsDesc: "血液検査を理解する",
    help_title: "🚀 Quick Start Guide",
    help_step1: "Just start typing! Describe your symptoms or ask a health question in the box at the bottom.",
    help_step2: "AI is not a doctor. We provide information, not medical advice. Always consult a professional.",
    help_step3: "Privacy First. Your data stays on your computer. Look for the 100% Private badge.",
    help_step4: "Emergency? If you have severe symptoms, call 911 or your local emergency number immediately.",
    help_got_it: "Got it!",
    tab_server: "Server",
    tab_customization: "Customization",
    tab_language: "Language",
    tab_features: "Features",
    tab_clinical: "My Clinical Profile",
    tab_troubleshooting: "Troubleshooting",
    server_config_title: "Server Configuration",
    server_config_desc: "Configure your AI backend connection",
    custom_title: "Customization",
    custom_desc: "Personalize your interface appearance",
    lang_title: "Language",
    lang_desc: "Select your preferred language",
    features_title: "Features",
    features_desc: "Enable or disable additional features",
    clinical_title: "My Clinical Profile",
    clinical_desc: "Your medical information helps the AI provide personalized advice",
    trouble_title: "Troubleshooting",
    trouble_desc: "Diagnostic tools and common issue fixes",
    label_ai_backend: "AI Backend",
    label_gemma_key: "Gemma API Key",
    label_openrouter_key: "OpenRouter Key",
    label_theme: "Theme",
    label_research: "Research Mode (Wikipedia when online)",
    label_camera: "Enable Camera Button",
    label_voice: "Read Responses Aloud (TTS)",
    label_allergies: "Allergies",
    label_conditions: "Medical Conditions",
    label_medications: "Current Medications",
    label_age: "Age",
    label_weight: "Weight (kg)",
    label_notes: "Additional Notes",
    hint_allergies: "List all known allergies, separated by commas",
    hint_conditions: "Chronic conditions or ongoing health issues",
    hint_medications: "Include dosages if known. This helps avoid drug interaction warnings.",
    btn_save_profile: "Save Profile",
    trouble_diag_title: "Connection Diagnostics",
    trouble_sys_title: "System Information",
    trouble_faq_title: "Common Issues",
    clinical_disclaimer: "This data is stored locally on your device and sent with chat requests to personalize AI responses.",
    privacy_badge_text: "100% Local & Encrypted",
    history_label: "チャット履歴",
    search_title: "Search Sessions",
    camera_take: "Take a Photo",
    camera_cancel: "Cancel",
    camera_capture: "Capture",
    mood_note_placeholder: "Add a note (optional)...",
    faq_slow: "AI responses are slow or timing out",
    faq_pdf: "PDF import is not working",
    faq_camera: "Camera button not appearing",
    faq_lang: "Language not changing",
  },
  ko: { 
    appTitle: "Gemma Health Edge",
    disclaimer_title: "의료 면책 조항", 
    disclaimer_text: "이 AI 건강 도우미는 교육 목적으로만 정보를 제공합니다...", 
    disclaimer_accept: "이해함", 
    settings_title: "설정",
    status_checking: "확인 중…",
    status_online: "온라인",
    status_offline: "오프라인",
    input_placeholder: "증상을 설명하세요...",
    welcome_title: "Gemma Health Edge",
    welcome_subtitle: "고급 오프라인 의료 인텔리전스 대시보드",
    settings_thinking: "思考を表示",
    toast_copied: "복사됨!",
    toast_saved: "저장됨!",
    toast_error: "오류",
    thinking: "생각 중…",
    newSession: "새 채팅",
    serverOnline: "온라인",
    serverOffline: "오프라인",
    autoDetect: "자동 감지",
    calendarTitle: "건강 캘린더",
    moodLabel: "기분",
    moodAverage: "이번 달 평균",
    cameraButton: "카메라",
    galleryButton: "갤러리",
    researchNote: "🔬 위키 배경 추가됨",
    notADoctor: "저는 의사가 아닙니다. 항상 의료 전문가와 상담하세요.",
    sessionHistory: "검색",
    clearChat: "지우기",
    help: "도움말",
    btn_clear_chat: "지우기",
    copyMessage: "복사",
    exportChat: "내보내기",
    privacyBadge: "100% 비공개",
    healthSector: "건강 분야",
    moodQuestion: "오늘 기분이 어떠신가요?",
    moodNotePlaceholder: "노트 추가 (선택 사항)...",
    medicalDisclaimer: "Medical Disclaimer",
    disclaimerText: "This assistant provides information only. It is not a substitute for professional medical advice, diagnosis, or treatment.",
    hwHardware: "하드웨어",
    hwVRAM: "VRAM",
    hwAcceleration: "가속",
    hwTTFT: "TTFT",
    hwTPS: "TPS",
    hwTotalTime: "총 시간",
    hwPrivacyMode: "개인정보 보호 모드",
    hwPrivacyValue: "100% 오프라인",
    cardSymptomChecker: "증상 확인",
    cardSymptomDesc: "두통과 경미열",
    cardMedicationInfo: "약물 정보",
    cardMedicationDesc: "이부프로페에 부작용",
    cardWellnessTips: "원래 팁",
    cardWellnessDesc: "수면 개선",
    cardHealthMetrics: "건강 지표",
    cardHealthDesc: "정상 혈압",
    cardNutrition: "영양",
    cardNutritionDesc: "건강한 식이구어",
    cardMentalHealth: "정신 건강",
    cardMentalDesc: "스트레스 관리",
    cardFitnessPlan: "피트니스 계획",
    cardFitnessDesc: "집에서 하는 운동",
    cardFirstAid: "응급 처치",
    cardFirstAidDesc: "경미 화상 처치",
    cardVaccinations: "예방 접종",
    cardVaccinationsDesc: "성인 접종 일정",
    cardLabResults: "검사 결과",
    cardLabResultsDesc: "혈액 검사 이해하기",
    help_title: "🚀 Quick Start Guide",
    help_step1: "Just start typing! Describe your symptoms or ask a health question in the box at the bottom.",
    help_step2: "AI is not a doctor. We provide information, not medical advice. Always consult a professional.",
    help_step3: "Privacy First. Your data stays on your computer. Look for the 100% Private badge.",
    help_step4: "Emergency? If you have severe symptoms, call 911 or your local emergency number immediately.",
    help_got_it: "Got it!",
    tab_server: "Server",
    tab_customization: "Customization",
    tab_language: "Language",
    tab_features: "Features",
    tab_clinical: "My Clinical Profile",
    tab_troubleshooting: "Troubleshooting",
    server_config_title: "Server Configuration",
    server_config_desc: "Configure your AI backend connection",
    custom_title: "Customization",
    custom_desc: "Personalize your interface appearance",
    lang_title: "Language",
    lang_desc: "Select your preferred language",
    features_title: "Features",
    features_desc: "Enable or disable additional features",
    clinical_title: "My Clinical Profile",
    clinical_desc: "Your medical information helps the AI provide personalized advice",
    trouble_title: "Troubleshooting",
    trouble_desc: "Diagnostic tools and common issue fixes",
    label_ai_backend: "AI Backend",
    label_gemma_key: "Gemma API Key",
    label_openrouter_key: "OpenRouter Key",
    label_theme: "Theme",
    label_research: "Research Mode (Wikipedia when online)",
    label_camera: "Enable Camera Button",
    label_voice: "Read Responses Aloud (TTS)",
    label_allergies: "Allergies",
    label_conditions: "Medical Conditions",
    label_medications: "Current Medications",
    label_age: "Age",
    label_weight: "Weight (kg)",
    label_notes: "Additional Notes",
    hint_allergies: "List all known allergies, separated by commas",
    hint_conditions: "Chronic conditions or ongoing health issues",
    hint_medications: "Include dosages if known. This helps avoid drug interaction warnings.",
    btn_save_profile: "Save Profile",
    trouble_diag_title: "Connection Diagnostics",
    trouble_sys_title: "System Information",
    trouble_faq_title: "Common Issues",
    clinical_disclaimer: "This data is stored locally on your device and sent with chat requests to personalize AI responses.",
    privacy_badge_text: "100% Local & Encrypted",
    history_label: "채팅 내역",
    search_title: "Search Sessions",
    camera_take: "Take a Photo",
    camera_cancel: "Cancel",
    camera_capture: "Capture",
    mood_note_placeholder: "Add a note (optional)...",
    faq_slow: "AI responses are slow or timing out",
    faq_pdf: "PDF import is not working",
    faq_camera: "Camera button not appearing",
    faq_lang: "Language not changing",
  }
};

const SUPPORTED_LANGS = Object.keys(dictionary);
const t = (key, lang = 'en') => (dictionary[lang] || dictionary.en)[key] || dictionary.en[key] || key;
const i18n = (lang) => ({ t: (key) => t(key, lang) });

// ── Persistence ──────────────────────────────────────────────────────────────

const Storage = {
  get: (key, defaultValue = null) => { 
    try { 
      const item = localStorage.getItem(key); 
      return item ? JSON.parse(item) : defaultValue; 
    } catch (e) { 
      console.error('[Storage] Get failed:', e); 
      return defaultValue; 
    } 
  },
  set: (key, value) => { 
    try { 
      localStorage.setItem(key, JSON.stringify(value)); 
      return true; 
    } catch (e) { 
      console.error('[Storage] Set failed:', e); 
      return false; 
    } 
  },
  remove: (key) => localStorage.removeItem(key),
  clear: () => localStorage.clear(),
};

// ── Configuration ────────────────────────────────────────────────────────────

const DEFAULT_CONFIG = {
  apiMode: 'local', 
  middlemanUrl: 'http://127.0.0.1:8080', 
  theme: 'dark', 
  lang: 'en',
  showThinking: true, 
  researchMode: true,
  cameraEnabled: false, 
  voiceEnabled: false,
  accentColor1: '#4285f4', 
  accentColor2: '#8b5cf6', 
  accentColor3: '#ec4899',
};

const Config = {
  get: (key) => { 
    const cfg = Storage.get('config', {}); 
    return cfg[key] !== undefined ? cfg[key] : DEFAULT_CONFIG[key]; 
  },
  set: (key, value) => {
    const cfg = Storage.get('config', {}); 
    cfg[key] = value; 
    return Storage.set('config', cfg);
  },
  getAll: () => ({ ...DEFAULT_CONFIG, ...Storage.get('config', {}) }),
  reset: () => Storage.set('config', {}),
};

// ── API Helpers ──────────────────────────────────────────────────────────────

const getAPIBase = () => Config.get('middlemanUrl') || 'http://127.0.0.1:8080';

const apiFetch = async (endpoint, options = {}) => {
  const url = `${getAPIBase()}${endpoint}`;
  try {
    const response = await fetch(url, {
      ...options,
      headers: { 'Content-Type': 'application/json', ...options.headers },
    });
    return { ok: response.ok, status: response.status, data: response.ok ? await response.json() : null };
  } catch (e) {
    console.error(`[API] Fetch failed for ${endpoint}:`, e);
    return { ok: false, error: e };
  }
};

const ChatStorage = {
  _key: 'ghe_sessions',

  _all: () => Storage.get(ChatStorage._key, []),

  getSessions: async () => {
    const local = ChatStorage._all();
    apiFetch('/api/v1/data/sessions').then(r => {
      if (r.ok && Array.isArray(r.data) && r.data.length > 0) Storage.set(ChatStorage._key, r.data);
    }).catch(() => {});
    return local;
  },

  getSession: async (id) => {
    const local = ChatStorage._all().find(s => s.id === id);
    apiFetch(`/api/v1/data/sessions/${id}`).then(r => {
      if (r.ok && r.data && typeof r.data === 'object') {
        const all = ChatStorage._all();
        const idx = all.findIndex(s => s.id === id);
        if (idx >= 0) { all[idx] = r.data; Storage.set(ChatStorage._key, all); }
      }
    }).catch(() => {});
    return local || null;
  },

  deleteSession: async (id) => {
    const all = ChatStorage._all().filter(s => s.id !== id);
    Storage.set(ChatStorage._key, all);
    apiFetch(`/api/v1/data/sessions/${id}`, { method: 'DELETE' }).catch(() => {});
    return true;
  },

  saveSession: async (session) => {
    const all = ChatStorage._all();
    const idx = all.findIndex(s => s.id === session.id);
    if (idx >= 0) { all[idx] = session; } else { all.push(session); }
    Storage.set(ChatStorage._key, all);
    apiFetch(`/api/v1/data/sessions/${session.id}`, { method: 'PUT', body: JSON.stringify(session) }).catch(() => {});
    return true;
  },

  clear: async () => {
    Storage.set(ChatStorage._key, []);
    apiFetch('/api/v1/data/sessions').then(r => {
      if (r.ok && Array.isArray(r.data)) r.data.forEach(s => ChatStorage.deleteSession(s.id));
    }).catch(() => {});
  }
};

const ClinicalProfile = {
  get: () => apiFetch('/api/v1/data/profile').then(r => r.data || {}),
  save: (data) => apiFetch('/api/v1/data/profile', { method: 'POST', body: JSON.stringify(data) }).then(r => r.ok),
  clear: () => ClinicalProfile.save({}),
};

const MoodTracker = {
  getHistory: (year, month) => apiFetch(`/api/v1/data/moods?year=${year}&month=${month}`).then(r => r.data || { history: {} }),
  saveMood: (date, mood, note = '') => apiFetch('/api/v1/data/moods', { method: 'POST', body: JSON.stringify({ date, mood, note }) }).then(r => r.ok),
};

const copyToClipboard = async (text) => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (e) {
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.style.position = 'fixed'; ta.style.opacity = '0';
    document.body.appendChild(ta);
    ta.select();
    document.execCommand('copy');
    document.body.removeChild(ta);
    return true;
  }
};

// ── Utilities ────────────────────────────────────────────────────────────

const generateId = () => Date.now().toString(36) + Math.random().toString(36).substr(2, 5);

const showToast = (message, type = 'info') => {
  const existing = document.querySelector('.toast-notification');
  if (existing) existing.remove();
  
  const toast = document.createElement('div');
  toast.className = `toast-notification toast-${type}`;
  toast.textContent = message;
  document.body.appendChild(toast);
  
  setTimeout(() => {
    toast.classList.add('fade-out');
    setTimeout(() => toast.remove(), 300);
  }, 3000);
};

async function detectGPU() {
  const info = { gpu: 'Unknown', vram: 'Unknown', accel: 'CPU', npu: null };
  if (!navigator.gpu) return info;
  try {
    const adapter = await navigator.gpu.requestAdapter();
    if (adapter) {
      const adapterInfo = await adapter.requestAdapterInfo();
      info.gpu = adapterInfo.description || adapterInfo.vendor || 'WebGPU Device';
      info.accel = 'WebGPU';
      if (adapterInfo.memory) info.vram = `${(adapterInfo.memory / 1024 / 1024 / 1024).toFixed(1)} GB`;
    }
  } catch (e) {
    console.debug('[Hardware] WebGPU detection bypassed.');
  }
  return info;
}

const resizeImage = (file, max = 512) => {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      let { width: w, height: h } = img;
      if (w > max || h > max) {
        const r = Math.min(max / w, max / h);
        w *= r; h *= r;
      }
      const canvas = document.createElement('canvas');
      canvas.width = w; canvas.height = h;
      canvas.getContext('2d').drawImage(img, 0, 0, w, h);
      canvas.toBlob(blob => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result);
        reader.readAsDataURL(blob);
      }, 'image/jpeg', 0.85);
    };
    img.src = URL.createObjectURL(file);
  });
};

const sanitizeHTML = (str) => {
  if (!str) return '';
  const div = document.createElement('div');
  div.textContent = str;
  return div.innerHTML;
};

const formatMarkdown = (text) => {
  if (!text) return '';
  return sanitizeHTML(text)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`(.+?)`/g, '<code>$1</code>')
    .replace(/\n/g, '<br>');
};

// ── Exports ──────────────────────────────────────────────────────────────────

window.GHE = window.GHE || {};
window.GHE.Core = {
  t, i18n, SUPPORTED_LANGS, dictionary,
  Storage, Config, DEFAULT_CONFIG,
  ChatStorage, ClinicalProfile, MoodTracker,
  generateId, showToast, detectGPU, resizeImage,
  sanitizeHTML, formatMarkdown, getAPIBase,
  copyToClipboard
};
window.Core = window.GHE.Core;
